println("2-2.0","@#%^&! ",2+2) # separated by comma
println(2+3)
println(2. +3)
println(2. +3.)
println(typeof(2. +3))
println(typeof(2+3))
println(typeof(2. +3.))
println(2+(2+3im))
println(2. + (2 + 3im))
println(Rational(2,3))
println(Rational(2,3)+2)
println(Rational(2,3)+2.0)
println(Rational(2,3)+ (2+3im))
println(Rational(2,3)+ (2+3im) + 3.0)
println(MathConstants.e)
println(MathConstants.pi)
println(MathConstants.eulergamma)
println(true + true)
println(true + false)
println(false + false)
println(false + true)
println(true + 0.1)
println(pi + MathConstants.e + 1 + 1.5 + true + false + true + Rational(2,3) + (2 + 3im))
println(true == false)
println(false == false)
println(2//3*8)
println(Rational(2, 3)*8)